// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uldgwssjsmkprywjeoyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsZGd3c3Nqc21rcHJ5d2plb3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTAzNTksImV4cCI6MjA3MzYyNjM1OX0.u7iejXGyWc_fBAK7jWNpqkkZCusvZBHXIxpM5Ij5h4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});